version: "3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    environment:
      - VIRTUAL_HOST

volumes:
  data:

networks:
  default:
    name: nginx-proxy
