version: "3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    # command: -H unix:///var/run/docker.sock
    expose:
      - 9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT=9443

volumes:
  data:

networks:
  default:
    name: nginx-proxy
