version: "3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT=9443

volumes:
  portainer_data:

networks:
  default:
    name: nginx-proxy
